### PR TITLE
Create Demo.txt

### PR DESCRIPTION
**Pull request by ashamold2002**
Hi Kavin,
Please review my file.

### CODE REVIEW

**Comment by Kavin-prakash** [comment]
I have reviewed your entire file, I found some changes.
 Please make some changes in these files

Change the Constant into Uppercase

**Comment by ashamold2002** [comment]
Thanks Kavin, I changed the file as you
 mentioned above.
 Could please verify it once again
 for any more errors.

**Comment by Kavin-prakash** [comment]
Its Good now,If you maintain the coding standards like
 whites paces it will be some more better.

**Comment by ashamold2002** [comment]
Yeah Kavin changed that also. 
Anything else?

**Comment by Kavin-prakash** [comment]
Yes everything is fine. If you add comments in the code
 it will be helpful for understanding easily.

**Comment by ashamold2002** [comment]
Thanks for spending your time to review 
my project Kavin.

**Comment by Kavin-prakash** [comment]
Thank You.

**Pull request merged**
